const collectionConstants = {
    LOAD_COLLECTIONS: 'LOAD_COLLECTIONS',
    SELECT_COLLECTION: 'SELECT_COLLECTION',
    SEARCH_COLLECTIONS: 'SEARCH_COLLECTIONS',
    ADD_MOVIE: 'ADD_MOVIE',
    REMOVE_MOVIE: 'REMOVE_MOVIE'
};

export default collectionConstants;
