const modalConstants = {
    OPEN_ADD_MOVIE_DIALOG: 'OPEN_ADD_MOVIE_DIALOG',
    CLOSE_ADD_MOVIE_DIALOG: 'CLOSE_ADD_MOVIE_DIALOG',
    SHOW_ORDER_DETAILS: 'SHOW_ORDER_DETAILS',
    GET_AUTOCOMPLETE: 'GET_AUTOCOMPLETE',
    CLOSE_AUTOCOMPLETE: 'CLOSE_AUTOCOMPLETE',
    SHOW_MOVIE_DETAILS: 'SHOW_MOVIE_DETAILS',
    HIDE_MOVIE_DETAILS: 'HIDE_MOVIE_DETAILS'
};

export default modalConstants;